name       : alsa-tools
version    : 1.1.7
release    : 5
source     :
    - ftp://ftp.alsa-project.org/pub/tools/alsa-tools-1.1.7.tar.bz2 : a0243328a8f6f691a3055c484fd8d3326393096325e93743b246029d327c4ef6
license    : GPL-2.0-or-later
component  : system.utils
summary    : Advanced soundcard tools
description: |
    The ALSA Tools package contains advanced tools for certain sound cards.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xft)
    - fltk-devel
build      : |
    %patch -p1 < $pkgfiles/0001-Ensure-modprobe.d-directory-exists-before-copying-fi.patch
    sed -i "s|hwmixvolume||" Makefile
    sed -i "s|qlo10k1||" Makefile
    export CONFIGURE_ARGS="%CONFOPTS%"
    %make configure
install    : |
    %make_install exec_prefix=/usr prefix=/usr
