name       : alsa-tools
version    : 1.1.0
release    : 1
source     :
    - ftp://ftp.alsa-project.org/pub/tools/alsa-tools-1.1.0.tar.bz2 : 7d34558c590a50294b36576d257316a1ac5cd951eb8cd7d330e09f8cc757ab51
license    :
    - GPL-2.0
    - MIT
component  : system.utils
summary    : Advanced soundcard tools
description: |
    The ALSA Tools package contains advanced tools for certain sound cards.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xft)
    - fltk-devel
build      : |
    sed -i "s|hwmixvolume||" Makefile
    sed -i "s|qlo10k1||" Makefile
    export CONFIGURE_ARGS="%CONFOPTS%"
    %make configure
install    : |
    %make_install exec_prefix=/usr prefix=/usr
