name       : alsa-tools
version    : 1.2.2
release    : 8
source     :
    - ftp://ftp.alsa-project.org/pub/tools/alsa-tools-1.2.2.tar.bz2 : bfd3c7aae1289269605d3da02279159b10e3dabdd31e658cbceaa30170957349
license    : GPL-2.0-or-later
component  : system.utils
summary    : Advanced soundcard tools
description: |
    The ALSA Tools package contains advanced tools for certain sound cards.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xft)
    - fltk-devel
build      : |
    %patch -p1 < $pkgfiles/0001-Ensure-modprobe.d-directory-exists-before-copying-fi.patch
    sed -i "s|hwmixvolume||" Makefile
    sed -i "s|qlo10k1||" Makefile
    export CONFIGURE_ARGS="%CONFOPTS% hotplugdir=/usr/share/alsa/hotplug/usb"
    hotplugdir=/usr/share/alsa/hotplug/usb %make configure
install    : |
    %make_install exec_prefix=/usr hotplugdir=/usr/share/alsa/hotplug/usb prefix=/usr
