name       : alsa-tools
version    : 1.1.3
release    : 2
source     :
    - ftp://ftp.alsa-project.org/pub/tools/alsa-tools-1.1.3.tar.bz2 : d88f1dcd6872121383eded5fa24e328e68c54e527db4547e1435d5eabc2b6709
license    :
    - GPL-2.0
    - MIT
component  : system.utils
summary    : Advanced soundcard tools
description: |
    The ALSA Tools package contains advanced tools for certain sound cards.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xft)
    - fltk-devel
build      : |
    sed -i "s|hwmixvolume||" Makefile
    sed -i "s|qlo10k1||" Makefile
    export CONFIGURE_ARGS="%CONFOPTS%"
    %make configure
install    : |
    %make_install exec_prefix=/usr prefix=/usr
